### ISSUE TITLE
Command line parameters for Azure Pipelines agent config.sh

### ISSUE THREAD

**Issue by jfpanisset** [g3rv4/terraform-pipeline-agent#1]
This is a very minor nitpick and definitely a question of preferences, but the config.sh script to configure the Azure Pipelines agent accepts additional command line parameter which would prevent having to set environment variables as a way to pass those parameters in agent.tf

So you could do something like:

```
./config.sh --unattended --acceptTeeEula --replace --url https://dev.azure.com/${var.pipelines_org} --auth pat --token https://dev.azure.com/${var.pipelines_org} --pool ${var.pipelines_pool_name} --agent ${var.agent_name}
```

(not sure how to format that in non ugly way). Those command line options are documented at:

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops

and may be longer term more robust than the VSTS_ environment variables?

**Comment by g3rv4** [comment]
thanks! I either never found that documented or I took the bad decision of preferring env variables.

want to submit a PR with the change?

**Comment by jfpanisset** [comment]
Done, see PR https://github.com/g3rv4/terraform-pipeline-agent/pull/2

Thank you very much for writing a great blog post entry at https://g3rv4.com/2019/11/azure-pipelines-auto-privisioning-agents I was able to get my own project to work using some of the methods you outlined in the blog and this code (needed a Azure Pipelines agent with a GPU to run a test suite that requires GPU access).
